routes/web.php
<?php

use App\Http\Controllers\Post\OpinionController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'verify' => true,
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])
    ->name('home');

Route::middleware('auth')->group(function(){
    
    Route::resource('post', PostController::class);
    Route::resource('post.opinion', OpinionController::class)->only('store');
    Route::post('/post/{post}/restore', [PostController::class, 'restore'])->name('post.restore');
    Route::delete('/post/{post}/force', [PostController::class, 'forceDestroy'])->name('post.forceDestroy');
    Route::delete('/post/{post}/destroyImage', [PostController::class, 'destroyImage'])->name('post.destroyImage');

});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use HasFactory, SoftDeletes;

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function opinions()
    {
        return $this->hasMany(Opinion::class);
    }

    public function scopeSearch(Builder $builder, $search)
    {
        $builder
            ->where(function(Builder $subBuilder) use ($search) {
                $subBuilder
                    ->where('title', 'LIKE', '%' . $search . '%')
                    ->orWhere('content', 'LIKE', '%' . $search . '%');
            });
    }
}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\User;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $posts = Post::query()
            ->when($request->query('search'), function(Builder $builder, $search){
                $builder->search($search);
            })
            ->latest('updated_at')
            ->withTrashed()
            ->paginate();

        return $posts;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => ['required', 'min:5'],
            'content' => ['required', 'min:10'],
        ]);

        $title = $request->get('title');
        $content = $request->get('content');

        $post = new Post();
        $post->user_id = auth()->id();
        $post->title = $title;
        $post->content = $content;
        $post->save();

        return $post;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return $post;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $request->validate([
            'title' => ['required', 'min:5'],
            'content' => ['required', 'min:10'],
        ]);

        $title = $request->get('title');
        $content = $request->get('content');

        $post->title = $title;
        $post->content = $content;
        $post->save();

        return $post;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        return $post->delete();
    }
}

app/Http/Controllers/Post/OpinionController.php
<?php

namespace App\Http\Controllers\Post;

use App\Http\Controllers\Controller;
use App\Models\Opinion;
use App\Models\Post;
use Illuminate\Http\Request;

class OpinionController extends Controller
{

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Post $post)
    {
        $request->validate([
            'mark' => ['required', 'numeric', 'in:1,2,3,4,5'],
        ]);

        $user = $request->user();

        $post
            ->opinions()
            ->getQuery()
            ->updateOrCreate([
                'user_id' => $user->id,
                'post_id' => $post->id,
            ], [
                'mark' => $request->get('mark'),
            ]);

        return redirect()->back();
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class PostController extends Controller
{

    public function create(Request $request)
    {
        return view('post.create');
    }
    
    public function store(Request $request)
    {
        $request->validate([
            'title' => ['required', 'min:5'],
            'content' => ['required', 'min:10'],
        ]);

        $title = $request->get('title');
        $content = $request->get('content');

        $post = new Post();
        $post->user_id = auth()->id();
        $post->title = $title;
        $post->content = $content;
        $post->save();

        return redirect()->route('post.edit', $post);
    }

    public function update(Request $request, Post $post)
    {
        $request->validate([
            'title' => ['required', 'min:5'],
            'content' => ['required', 'min:10'],
            'image' => ['image', 'max:2048'],
        ]);

        if($request->hasFile('image')) {
            $file = $request->file('image');

            $path = $file->store('/public/posts');

            $post->image = Str::of($path)->replace('public', 'storage')->start('/');
        }

        $title = $request->get('title');
        $content = $request->get('content');

        $post->title = $title;
        $post->content = $content;
        $post->save();

        return redirect()->back();
    }

    public function edit(Request $request, Post $post)
    {
        return view('post.edit', [
            'post' => $post,
        ]);
    }

    public function show(Request $request, Post $post)
    {
        $opinion = $post
            ->opinions()
            ->getQuery()
            ->where('user_id', auth()->id())
            ->firstOrNew();

        $post->loadAvg('opinions', 'mark');

        return view('post.show', [
            'post' => $post,
            'opinion' => $opinion,
        ]);
    }

    public function destroy(Request $request, Post $post)
    {
        $post->delete();

        return redirect()->back();
    }

    public function destroyImage(Request $request, Post $post)
    {
        Storage::delete(storage_path('app' . Str::of($post->image)->replace('storage', 'public')));

        $post->image = null;
        $post->save();

        return redirect()->back();
    }

    public function forceDestroy(Request $request, $postId)
    {
        Post::query()->withTrashed()->findOrFail($postId)->forceDelete();

        return redirect()->back();
    }

    public function restore(Request $request, $postId)
    {
        Post::query()->withTrashed()->findOrFail($postId)->restore();

        return redirect()->back();
    }

}

resources/views/post/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul class="mb-0 pl-0">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ route('post.store') }}" method="POST">
                        @csrf

                        <div class="mb-3">
                            <label for="title" class="form-label">Titre</label>
                            <input type="text" class="form-control" name="title" id="title">
                        </div>
                        <div class="mb-3">
                            <label for="content" class="form-label">Contenu</label>
                            <textarea class="form-control" name="content" id="content" rows="3"></textarea>
                        </div>

                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul class="mb-0 pl-0">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ route('post.destroyImage', $post) }}" id="post-delete-image" method="post">
                        @csrf
                        @method('DELETE')
                    </form>

                    <form action="{{ route('post.update', $post) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')

                        <div class="mb-3">
                            <label for="title" class="form-label">Titre</label>
                            <input type="text" class="form-control" value="{{ $post->title }}" name="title" id="title">
                        </div>
                        <div class="mb-3">
                            <label for="content" class="form-label">Contenu</label>
                            <textarea class="form-control" name="content" id="content" rows="3">{{ $post->content }}</textarea>
                        </div>

                        <div class="mb-3">
                            <img src="{{ $post->image }}" height="100">
                            <br>

                            <a href="#" onclick="event.preventDefault(); document.querySelector('#post-delete-image').submit()" class="text-danger">Supprimer l'image</a>

                            <hr>

                            <label for="image" class="form-label">Image</label>
                            <input type="file" accept="image/*" class="form-control" name="image" id="image">
                        </div>
                        

                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul class="mb-0 pl-0">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="#" method="POST">

                        <div class="mb-3">
                            <label for="title" class="form-label">Titre</label>
                            <input disabled type="text" class="form-control" value="{{ $post->title }}" name="title" id="title">
                        </div>
                        <div class="mb-3">
                            <label for="content" class="form-label">Contenu</label>
                            <textarea disabled class="form-control" name="content" id="content" rows="3">{{ $post->content }}</textarea>
                        </div>

                        <div class="mb-3">
                            <img src="{{ $post->image }}" width="100%">
                        
                            <hr>

                            <label for="image" class="form-label">Image</label>
                            <input disabled type="file" accept="image/*" class="form-control" name="image" id="image">
                        </div>
                        
                    </form>

                    <a href="{{ route('post.edit', $post) }}" class="btn btn-primary">Editer</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">

            <div class="card mb-3">
                <div class="card-body">
                    <h3>Avis</h3>

                    <hr>

                    <form action="{{ route('post.opinion.store', $post) }}" method="post">
                        @csrf

                        <div>
                            <select class="form-control" name="mark" id="mark">
                                <option value="1">1/5</option>
                                <option value="2">2/5</option>
                                <option value="3">3/5</option>
                                <option value="4">4/5</option>
                                <option value="5">5/5</option>
                            </select>
                        </div>

                        <button type="submit" class="btn btn-primary w-100 mt-1">Valider mon avis</button>
                    </form>
                    
                    @if ($opinion->exists)
                    <p class="mb-0 mt-3 lead">Mon avis : {{ $opinion->mark }} / 5</p>
                    @endif

                    <p class="mb-0 mt-3 lead">Moyenne d'avis {{ number_format($post->opinions_avg_mark, 2, '.', ' ') }} / 5</p>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <h3>Commentaire</h3>
                    <hr>

                    <div class="card mb-2">
                        <div class="card-body small">
                            <span class="small">
                                This is some text within a card body.
                            </span>
                        </div>
                        <div class="card-footer small">
                            <span class="small">By Hicham - 24/12/22</span>
                        </div>
                    </div>

                    <form action="#" method="#">
                        <div class="card">
                            <div class="card-body p-0 small">
                                <textarea class="w-100 h-100 border-0" name="comment" id="comment" cols="30" rows="5"></textarea>
                            </div>
                            
                            <button type="submit" class="btn btn-primary mt-1">Ajouter un commentaire</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection